server:
  port: 8110

spring:
  batch:
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:mysql://batch_test:3306/batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r
